export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ORGANIZATION_REPOSITORY = 'ORGANIZATION_REPOSITORY';
export const MARKETPLACE_REPOSITORY = 'MARKETPLACE_REPOSITORY';
export const WAREHOUSE_REPOSITORY = 'WAREHOUSE_REPOSITORY';
export const REMNANTS_REPOSITORY = 'REMNANTS_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const ORGANIZATION_PRODUCT_REPOSITORY =
  'ORGANIZATION_PRODUCT_REPOSITORY';
export const BOX_REPOSITORY = 'BOX_REPOSITORY';
export const ACCEPTANCE_REPOSITORY = 'ACCEPTANCE_REPOSITORY';
export const ACCEPTANCE_ORGANIZATION_PRODUCT_REPOSITORY =
  'ACCEPTANCE_ORGANIZATION_PRODUCT_REPOSITORY';
export const INVENTARIZATION_REPOSITORY = 'INVENTARIZATION_REPOSITORY';
export const DISPOSAL_REPOSITORY = 'DISPOSAL_REPOSITORY';
export const DISPOSAL_PRODUCT_REPOSITORY = 'DISPOSAL_REPOSITORY';
export const FBO_REPOSITORY = 'FBO_REPOSITORY';
export const CAR_REPOSITORY = 'CAR_REPOSITORY';
export const PALLET_REPOSITORY = 'PALLET_REPOSITORY';
export const FBS_REPOSITORY = 'FBS_REPOSITORY';

export const FBS_ORDER_REPOSITORY = 'FBS_ORDER_REPOSITORY';
